<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>icu.debug.net.wg</groupId>
        <artifactId>wgnet-registry</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>wireguard-registry-storage</artifactId>
    <packaging>pom</packaging>
    <name>WireGuard Registry Storage</name>
    <description>存储层父模块</description>

    <modules>
        <module>memory</module>
        <module>sqlite</module>
    </modules>

</project>
